### ISSUE TITLE
Need a route from Admin spike approval page to list of currently displayed/approved spikes

### ISSUE THREAD

**Issue by kccrs** [Jeff-Duke/turing-fridays#17] opened 2017-01-03 02:00 UTC

**Comment by kerrd89** [comment] 2017-01-03 18:59
closing this since it is a duplicate of 24

**Comment by kccrs** [comment] 2017-01-04 17:46
This is not a duplicate of 24 - reopening.  This is not a style issue, it's a functionality issue.

**Comment by Jeff-Duke** [comment] 2017-01-05 01:16
I think @kerrd89 is working on a filtering function for the admin page to let an admin see approved, pending, all etc that should take care of this.

**Closed** 2017-01-05 16:52 UTC
Labels: MVP
